
package dbms;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.plaf.ColorUIResource;



public class login extends javax.swing.JFrame {

    
    

    public login() {
        initComponents();
        
        this.setFocusable(true);
        this.setLocationRelativeTo(null);
        
        // focus tranparent color 
        UIDefaults defaults = UIManager.getLookAndFeelDefaults();
        defaults.put("Button.focus", new ColorUIResource(new Color(0,0,0,0)));
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernametf1 = new javax.swing.JTextField();
        passtf1 = new javax.swing.JPasswordField();
        login_button = new javax.swing.JButton();
        create = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        minimize_1 = new javax.swing.JLabel();
        close_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/images/user.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/images/password.png"))); // NOI18N

        usernametf1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        usernametf1.setForeground(new java.awt.Color(153, 153, 153));
        usernametf1.setText("username");
        usernametf1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 7, 0, 0, new java.awt.Color(255, 255, 255)));
        usernametf1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernametf1.setMinimumSize(new java.awt.Dimension(9, 20));
        usernametf1.setSelectionColor(new java.awt.Color(204, 204, 204));
        usernametf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernametf1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernametf1FocusLost(evt);
            }
        });
        usernametf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametf1ActionPerformed(evt);
            }
        });
        usernametf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernametf1KeyPressed(evt);
            }
        });

        passtf1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passtf1.setForeground(new java.awt.Color(153, 153, 153));
        passtf1.setText("password");
        passtf1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 7, 0, 0, new java.awt.Color(255, 255, 255)));
        passtf1.setMinimumSize(new java.awt.Dimension(9, 20));
        passtf1.setSelectionColor(new java.awt.Color(204, 204, 204));
        passtf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passtf1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passtf1FocusLost(evt);
            }
        });
        passtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtf1ActionPerformed(evt);
            }
        });
        passtf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passtf1KeyPressed(evt);
            }
        });

        login_button.setBackground(new java.awt.Color(153, 153, 0));
        login_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_button.setForeground(new java.awt.Color(255, 255, 255));
        login_button.setText("Login");
        login_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        login_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_button.setRequestFocusEnabled(false);
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        create.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setText("Create Account");
        create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create.setRequestFocusEnabled(false);
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(passtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usernametf1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(usernametf1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(passtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(create)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 500, -1));

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setToolTipText("");
        jPanel4.setName("Login"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 25)); // NOI18N
        jLabel3.setText(" Hasan's Revo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 0, -1, -1));

        minimize_1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        minimize_1.setText(" - ");
        minimize_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        minimize_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_1MouseExited(evt);
            }
        });
        jPanel2.add(minimize_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 11, -1, -1));

        close_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close_2.setText(" x ");
        close_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        close_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_2MouseExited(evt);
            }
        });
        jPanel2.add(close_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 11, -1, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_2MouseExited
        Border label_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        close_2.setBorder(label_border);
        close_2.setForeground(Color.black);
    }//GEN-LAST:event_close_2MouseExited

    private void close_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_2MouseEntered
        Border label_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        close_2.setBorder(label_border);
        close_2.setForeground(Color.gray);
    }//GEN-LAST:event_close_2MouseEntered

    private void close_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_2MouseClicked

        System.exit(0);
    }//GEN-LAST:event_close_2MouseClicked

    private void minimize_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_1MouseExited
        Border label_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        minimize_1.setBorder(label_border);
        minimize_1.setForeground(Color.black);
    }//GEN-LAST:event_minimize_1MouseExited

    private void minimize_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_1MouseEntered
        Border label_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        minimize_1.setBorder(label_border);
        minimize_1.setForeground(Color.gray);
    }//GEN-LAST:event_minimize_1MouseEntered

    private void minimize_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_1MouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_1MouseClicked

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed

         
        PreparedStatement st;
        ResultSet rs;

        String username = usernametf1.getText();
        String password = String.valueOf(passtf1.getPassword());
        String fullname = null ;
        String mobile = null;
        String gender = null;
        
        
        String query = "SELECT * FROM `user` WHERE `username` = ? AND `password` = ?";
        
        if(usernametf1.getText().equals("")){
            
            JOptionPane.showMessageDialog(null,"Empty Username","Empty",2);
        }
        else if(passtf1.equals("")){
            
            JOptionPane.showMessageDialog(null,"Empty Password","Empty",2);
        }

        try {
            st = my_con.getConnection().prepareStatement(query);

            st.setString(1, username);
            st.setString(2, password);
            rs = st.executeQuery();

            if(rs.next()){
                
                String uname = rs.getString("username");
                FnClass.empname = uname;
//                
//                String fname = rs.getString("full_name");
//                FnClass.fullname = fname;
//                
//                String pass = rs.getString("password");
//                FnClass.password = pass;
//               
//                String mno = rs.getString("phone");
//                FnClass.mobile = mno;
//               
//                String gen = rs.getString("gender");
//                FnClass.gender = gen;
                
//                
//                BufferedImage im = ImageIO.read(rs.getBinaryStream("image"));
//                FnClass.img = (Blob) im;
                
     
                Main form = new Main();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);

                this.dispose();

            }
            else
            {
                usernametf1.setText("");
                passtf1.setText("");
                usernametf1.requestFocus();
                JOptionPane.showMessageDialog(null,"Invalid Username or Password!","Login Error", 2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void passtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtf1ActionPerformed
       
    }//GEN-LAST:event_passtf1ActionPerformed

    private void passtf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passtf1FocusLost

        String pass = String.valueOf(passtf1.getPassword());
        if(pass.trim().equals("")
            || pass.trim().toLowerCase().equals("password")){
            passtf1.setText("password");
            passtf1.setForeground(new Color(153,153,153));

        }

        Border field_border = BorderFactory.createMatteBorder(1, 7, 1, 1, Color.white);
        passtf1.setBorder(field_border);
    }//GEN-LAST:event_passtf1FocusLost

    private void passtf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passtf1FocusGained

        String pass = String.valueOf(passtf1.getPassword());
        if(pass.trim().toLowerCase().equals("password"))
        {
            passtf1.setText("");
            passtf1.setForeground(Color.black);
        }

        Border field_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        passtf1.setBorder(field_border);
    }//GEN-LAST:event_passtf1FocusGained

    private void usernametf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametf1ActionPerformed

    private void usernametf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernametf1FocusLost
        if(usernametf1.getText().trim().equals("")
            || usernametf1.getText().trim().toLowerCase().equals("username")){
            usernametf1.setText(" username");
            usernametf1.setForeground(new Color(153,153,153));

        }

        Border field_border = BorderFactory.createMatteBorder(1, 7, 1, 1, Color.white);
        usernametf1.setBorder(field_border);
    }//GEN-LAST:event_usernametf1FocusLost

    private void usernametf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernametf1FocusGained

        if(usernametf1.getText().trim().toLowerCase().equals("username"))
        {
            usernametf1.setText("");
            usernametf1.setForeground(Color.black);
        }

        Border field_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        usernametf1.setBorder(field_border);
        
        
    }//GEN-LAST:event_usernametf1FocusGained

    private void createMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseEntered
        
        create.setForeground(new Color(255,153,102));
        
    }//GEN-LAST:event_createMouseEntered

    private void createMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseExited
        
        create.setForeground(new Color(255,255,255));
        
    }//GEN-LAST:event_createMouseExited
   
    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
        
        verification vf = new verification();
        vf.setVisible(true);
        vf.pack();
        vf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_createMouseClicked

    private void usernametf1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernametf1KeyPressed
        
        int key = evt.getKeyCode();
        
        if(key == 10){
            passtf1.requestFocus();
        }
    }//GEN-LAST:event_usernametf1KeyPressed

    private void passtf1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passtf1KeyPressed
        
        int key = evt.getKeyCode();
        
        if(key == 10){
            login_button.doClick();
        }
    }//GEN-LAST:event_passtf1KeyPressed

 
    
    
    
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_2;
    private javax.swing.JLabel create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel minimize_1;
    private javax.swing.JPasswordField passtf1;
    private javax.swing.JTextField usernametf1;
    // End of variables declaration//GEN-END:variables
}
