/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Hasan Rafi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        login_name.setText(String.valueOf(FnClass.empname).toString());
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        billinglabel = new javax.swing.JLabel();
        profilelabel = new javax.swing.JLabel();
        productlabel = new javax.swing.JLabel();
        aboutlabel = new javax.swing.JLabel();
        salelabel = new javax.swing.JLabel();
        login_name = new javax.swing.JLabel();
        minimize_1 = new javax.swing.JLabel();
        minimize_2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        billinglabel.setBackground(new java.awt.Color(51, 51, 51));
        billinglabel.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        billinglabel.setForeground(new java.awt.Color(255, 255, 255));
        billinglabel.setText("      Booking");
        billinglabel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray, 2));
        billinglabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        billinglabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billinglabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billinglabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billinglabelMouseExited(evt);
            }
        });
        jPanel1.add(billinglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 200, 60));

        profilelabel.setBackground(java.awt.Color.gray);
        profilelabel.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        profilelabel.setForeground(new java.awt.Color(255, 255, 255));
        profilelabel.setText("        Profile");
        profilelabel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray, 2));
        profilelabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profilelabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilelabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilelabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilelabelMouseExited(evt);
            }
        });
        jPanel1.add(profilelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 200, 60));

        productlabel.setBackground(new java.awt.Color(51, 51, 51));
        productlabel.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        productlabel.setForeground(new java.awt.Color(255, 255, 255));
        productlabel.setText("      Routes");
        productlabel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray, 2));
        productlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productlabelMouseExited(evt);
            }
        });
        jPanel1.add(productlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 200, 60));

        aboutlabel.setBackground(new java.awt.Color(51, 51, 51));
        aboutlabel.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        aboutlabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutlabel.setText("        About");
        aboutlabel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray, 2));
        aboutlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutlabelMouseExited(evt);
            }
        });
        jPanel1.add(aboutlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 200, 60));

        salelabel.setBackground(new java.awt.Color(51, 51, 51));
        salelabel.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        salelabel.setForeground(new java.awt.Color(255, 255, 255));
        salelabel.setText("        Sales");
        salelabel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray, 2));
        salelabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salelabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salelabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salelabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salelabelMouseExited(evt);
            }
        });
        jPanel1.add(salelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 200, 60));

        login_name.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        login_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(login_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 80, 20));

        minimize_1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        minimize_1.setForeground(new java.awt.Color(255, 255, 255));
        minimize_1.setText(" - ");
        minimize_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        minimize_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_1MouseExited(evt);
            }
        });
        jPanel1.add(minimize_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, -1, -1));

        minimize_2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        minimize_2.setForeground(new java.awt.Color(255, 255, 255));
        minimize_2.setText(" x ");
        minimize_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        minimize_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_2MouseExited(evt);
            }
        });
        jPanel1.add(minimize_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/images/SignOut.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 42)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("    Revo Ticket Management System");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 670, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Login as:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 20));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/images/71462.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1200, 590));

        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Hasan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 220, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimize_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_1MouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_1MouseClicked

    private void minimize_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_1MouseEntered
        Border label_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.orange);
        minimize_1.setBorder(label_border);
        minimize_1.setForeground(Color.orange);
    }//GEN-LAST:event_minimize_1MouseEntered

    private void minimize_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_1MouseExited
        Border label_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        minimize_1.setBorder(label_border);
        minimize_1.setForeground(Color.white);
    }//GEN-LAST:event_minimize_1MouseExited

    private void minimize_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_2MouseClicked

        System.exit(0);
    }//GEN-LAST:event_minimize_2MouseClicked

    private void minimize_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_2MouseEntered
        Border label_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.orange);
        minimize_2.setBorder(label_border);
        minimize_2.setForeground(Color.orange);
    }//GEN-LAST:event_minimize_2MouseEntered

    private void minimize_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_2MouseExited
        Border label_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        minimize_2.setBorder(label_border);
        minimize_2.setForeground(Color.white);
    }//GEN-LAST:event_minimize_2MouseExited

    private void billinglabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billinglabelMouseEntered
      
       Border label_border=BorderFactory.createMatteBorder(2, 2, 2, 2, Color.orange);
        billinglabel.setBorder(label_border);
        billinglabel.setForeground(Color.orange);
       
    }//GEN-LAST:event_billinglabelMouseEntered

    private void profilelabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilelabelMouseEntered
       Border label_border=BorderFactory.createMatteBorder(2, 2, 2, 2, Color.orange);
        profilelabel.setBorder(label_border);
        profilelabel.setForeground(Color.orange);
    }//GEN-LAST:event_profilelabelMouseEntered

    private void productlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productlabelMouseEntered
       
        Border label_border=BorderFactory.createMatteBorder(2, 2, 2, 2, Color.orange);
        productlabel.setBorder(label_border);
        productlabel.setForeground(Color.orange);
    }//GEN-LAST:event_productlabelMouseEntered

    private void aboutlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutlabelMouseEntered
       
        Border label_border=BorderFactory.createMatteBorder(2, 2, 2, 2, Color.orange);
        aboutlabel.setBorder(label_border);
        aboutlabel.setForeground(Color.orange);
    }//GEN-LAST:event_aboutlabelMouseEntered

    private void salelabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salelabelMouseEntered
        
        Border label_border=BorderFactory.createMatteBorder(2, 2, 2, 2, Color.orange);
        salelabel.setBorder(label_border);
        salelabel.setForeground(Color.orange);
    }//GEN-LAST:event_salelabelMouseEntered

    private void billinglabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billinglabelMouseExited
      
        Border label_border=BorderFactory.createMatteBorder(2, 2, 2, 2, Color.gray);
        billinglabel.setBorder(label_border);
        billinglabel.setForeground(Color.white);
   
    }//GEN-LAST:event_billinglabelMouseExited

    private void profilelabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilelabelMouseExited
        
        Border label_border=BorderFactory.createMatteBorder(2, 2, 2, 2, Color.gray);
        profilelabel.setBorder(label_border);
        profilelabel.setForeground(Color.white);
    }//GEN-LAST:event_profilelabelMouseExited

    private void productlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productlabelMouseExited
        
        Border label_border=BorderFactory.createMatteBorder(2, 2, 2, 2, Color.gray);
        productlabel.setBorder(label_border);
        productlabel.setForeground(Color.white);
    }//GEN-LAST:event_productlabelMouseExited

    private void salelabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salelabelMouseExited
        
        Border label_border=BorderFactory.createMatteBorder(2, 2, 2, 2, Color.gray);
        salelabel.setBorder(label_border);
        salelabel.setForeground(Color.white);
    }//GEN-LAST:event_salelabelMouseExited

    private void aboutlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutlabelMouseExited
       
        Border label_border=BorderFactory.createMatteBorder(2, 2, 2, 2, Color.gray);
        aboutlabel.setBorder(label_border);
        aboutlabel.setForeground(Color.white);
    }//GEN-LAST:event_aboutlabelMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       
        int cnf = JOptionPane.showConfirmDialog(null, "    Sign Out Your Account  \n\n","Sign Out",JOptionPane.YES_NO_OPTION);

                        if(cnf == 0){
                            login lon = new login();
                            lon.setVisible(true);
                            lon.pack();
                            lon.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                            
                        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void billinglabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billinglabelMouseClicked

                            Billing bill = new Billing();
                            bill.setVisible(true);
                            bill.pack();
                            bill.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//                            this.dispose();
    }//GEN-LAST:event_billinglabelMouseClicked

    private void profilelabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilelabelMouseClicked
                           
        try {
            Profile pro = new Profile();
            pro.setVisible(true);
            pro.pack();
            pro.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
                           
    }//GEN-LAST:event_profilelabelMouseClicked

    private void productlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productlabelMouseClicked
        
                            Products product = new Products();
                            product.setVisible(true);
                            product.pack();
                            product.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_productlabelMouseClicked

    private void salelabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salelabelMouseClicked
      
                            Sales sale = new Sales();
                            sale.setVisible(true);
                            sale.pack();
                            sale.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_salelabelMouseClicked

    private void aboutlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutlabelMouseClicked
       
                            About about = new About();
                            about.setVisible(true);
                            about.pack();
                            about.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_aboutlabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutlabel;
    private javax.swing.JLabel billinglabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login_name;
    private javax.swing.JLabel minimize_1;
    private javax.swing.JLabel minimize_2;
    private javax.swing.JLabel productlabel;
    private javax.swing.JLabel profilelabel;
    private javax.swing.JLabel salelabel;
    // End of variables declaration//GEN-END:variables
}
