
package dbms;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.plaf.ColorUIResource;



public class verification extends javax.swing.JFrame {


    public verification() {
        initComponents();
        
        // focus tranparent color 
        UIDefaults defaults = UIManager.getLookAndFeelDefaults();
        defaults.put("Button.focus", new ColorUIResource(new Color(0,0,0,0)));
        hidechk.setSelected(true);
        this.setLocationRelativeTo(null);
         
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        minimize_1 = new javax.swing.JLabel();
        close_2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        verify = new javax.swing.JButton();
        backto = new javax.swing.JLabel();
        otptf1 = new javax.swing.JPasswordField();
        hidechk = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setToolTipText("");
        jPanel4.setName("Login"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 25)); // NOI18N
        jLabel3.setText("Verification");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        minimize_1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        minimize_1.setText(" - ");
        minimize_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        minimize_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_1MouseExited(evt);
            }
        });

        close_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close_2.setText(" x ");
        close_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        close_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_2MouseExited(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/images/password (1).png"))); // NOI18N

        verify.setBackground(new java.awt.Color(255, 102, 102));
        verify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        verify.setForeground(new java.awt.Color(255, 255, 255));
        verify.setText("Verify");
        verify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verify.setRequestFocusEnabled(false);
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });

        backto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        backto.setForeground(new java.awt.Color(255, 255, 255));
        backto.setText("Back To Login");
        backto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backtoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backtoMouseExited(evt);
            }
        });

        otptf1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        otptf1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 7, 0, 0, new java.awt.Color(255, 255, 255)));
        otptf1.setName(""); // NOI18N
        otptf1.setSelectionColor(new java.awt.Color(204, 204, 204));
        otptf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                otptf1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                otptf1FocusLost(evt);
            }
        });
        otptf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otptf1ActionPerformed(evt);
            }
        });
        otptf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                otptf1KeyPressed(evt);
            }
        });

        hidechk.setBackground(new java.awt.Color(102, 102, 102));
        hidechk.setForeground(new java.awt.Color(255, 255, 255));
        hidechk.setText("H I D E");
        hidechk.setContentAreaFilled(false);
        hidechk.setRequestFocusEnabled(false);
        hidechk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidechkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verify, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(otptf1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hidechk))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(otptf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hidechk)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)))
                .addComponent(verify, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(backto, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close_2)
                .addGap(9, 9, 9))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(close_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minimize_1)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_2MouseExited
        Border label_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        close_2.setBorder(label_border);
        close_2.setForeground(Color.black);
    }//GEN-LAST:event_close_2MouseExited

    private void close_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_2MouseEntered
        Border label_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        close_2.setBorder(label_border);
        close_2.setForeground(Color.gray);
    }//GEN-LAST:event_close_2MouseEntered

    private void close_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_2MouseClicked

        System.exit(0);
    }//GEN-LAST:event_close_2MouseClicked

    private void minimize_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_1MouseExited
        Border label_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        minimize_1.setBorder(label_border);
        minimize_1.setForeground(Color.black);
    }//GEN-LAST:event_minimize_1MouseExited

    private void minimize_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_1MouseEntered
        Border label_border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        minimize_1.setBorder(label_border);
        minimize_1.setForeground(Color.gray);
    }//GEN-LAST:event_minimize_1MouseEntered

    private void minimize_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_1MouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_1MouseClicked

    private void hidechkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidechkActionPerformed

        if(hidechk.isSelected()){
            otptf1.setEchoChar('*');
        }
        else{
            otptf1.setEchoChar((char)0);
        }
    }//GEN-LAST:event_hidechkActionPerformed

    private void otptf1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otptf1KeyPressed

        int key = evt.getKeyCode();

        if(key == 10){
            verify.doClick();
        }
    }//GEN-LAST:event_otptf1KeyPressed

    private void otptf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otptf1ActionPerformed

    }//GEN-LAST:event_otptf1ActionPerformed

    private void otptf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otptf1FocusLost

        Border field_border = BorderFactory.createMatteBorder(1, 7, 1, 1, Color.white);
        otptf1.setBorder(field_border);
    }//GEN-LAST:event_otptf1FocusLost

    private void otptf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otptf1FocusGained

        hidechk.setSelected(true);
        
        String pass = String.valueOf(otptf1.getPassword());
        if(pass.trim().equals("C O D E"))
        {
            otptf1.setText("");
            otptf1.setForeground(Color.black);
        }

        Border field_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        otptf1.setBorder(field_border);
    }//GEN-LAST:event_otptf1FocusGained

    private void backtoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtoMouseExited

        backto.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_backtoMouseExited

    private void backtoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtoMouseEntered

        backto.setForeground(new Color(255,153,102));
    }//GEN-LAST:event_backtoMouseEntered

    private void backtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtoMouseClicked

        login lon = new login();
        lon.setVisible(true);
        lon.pack();
        lon.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backtoMouseClicked

    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed

        String df = String.valueOf(otptf1.getPassword());

        if("hr2010".equals(df) || "Hasan10".equals(df)){

            registration form = new registration();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);

            this.dispose();

        }
        else
        {
            otptf1.setText("");
            JOptionPane.showMessageDialog(null,"Invalid Verification Code !","Verifiction Error", 2);
        }
    }//GEN-LAST:event_verifyActionPerformed
         
 
    
    
    
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backto;
    private javax.swing.JLabel close_2;
    private javax.swing.JCheckBox hidechk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel minimize_1;
    private javax.swing.JPasswordField otptf1;
    private javax.swing.JButton verify;
    // End of variables declaration//GEN-END:variables

    private void printf(String c, char c0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
